/**
 * Tenant administration (Power Platform admin centre).
 *
 * One entry per command; the flags come from `pac admin: tenant administration <command> help` on pac 2.11.2.
 */
import { ASYNC, ENV, SOLUTION_EXPORT, type PacCommandSpec } from "../pacParams.js";

export const SPECS: PacCommandSpec[] = [
  // These run as the tenant admin account: pass 'profile', or set CPS_ADMIN_PROFILE.
  {
    tool: "cs_admin_list_environments",
    title: "List environments (admin)",
    description: "Every environment in the tenant with its type, region and state, as the admin centre lists them. Filters by name, type or installed application.",
    command: ["admin", "list"],
    params: {
      environment: { flag: "--environment", type: "string", description: "Only environments whose name or id contains this text" },
      type: { flag: "--type", type: "string", description: "Only environments of this type (Production, Sandbox, Trial, Developer, Teams)" },
      name: { flag: "--name", type: "string", description: "Only environments whose name contains this text" },
      application: { flag: "--application", type: "string", description: "Only environments with this application installed" },
    },
    mutating: false,
  },
  {
    tool: "cs_admin_environment_status",
    title: "Operations in progress",
    description: "Status of the tenant operations that are still running (copies, restores, resets, deletions).",
    command: ["admin", "status"],
    params: {},
    mutating: false,
  },
  {
    tool: "cs_admin_list_tenant_settings",
    title: "Read tenant settings",
    description: "The tenant-wide Power Platform settings (governance, sharing, support, licensing). With settingsFile, pac writes them as JSON to that path; that file is the reference copy to keep in source control.",
    command: ["admin", "list-tenant-settings"],
    params: { settingsFile: { flag: "--settings-file", type: "string", description: "Write the settings to this .json file" } },
    mutating: false,
  },
  {
    tool: "cs_admin_update_tenant_settings",
    title: "Update tenant settings",
    description: "Change tenant-wide settings, either from a settings file or one setting at a time (for example powerPlatform.governance.disableDeveloperEnvironmentCreationByNonAdminUsers). Affects the whole tenant: requires confirm: true.",
    command: ["admin", "update-tenant-settings"],
    params: {
      settingsFile: { flag: "--settings-file", type: "string", description: "A .json file of settings (from cs_admin_list_tenant_settings)" },
      settingName: { flag: "--setting-name", type: "string", description: "Single setting path" },
      settingValue: { flag: "--setting-value", type: "string", description: "Value for that setting" },
    },
    mutating: true,
  },
  {
    tool: "cs_admin_list_dlp_policies",
    title: "List DLP policies",
    description: "Data loss prevention policies in the tenant: the connector groups that decide which connectors an agent or flow may combine.",
    command: ["admin", "dlp-policy", "list"],
    params: {},
    mutating: false,
  },
  {
    tool: "cs_admin_show_dlp_policy",
    title: "Show one DLP policy",
    description: "One data loss prevention policy in full: its connector classification and the environments it applies to.",
    command: ["admin", "dlp-policy", "show"],
    params: { policyName: { flag: "--policy-name", type: "string", required: true, description: "Policy id (GUID); cs_admin_list_dlp_policies shows it" } },
    mutating: false,
  },
  {
    tool: "cs_admin_list_environment_groups",
    title: "List environment groups",
    description: "Environment groups in the tenant (the grouping used for managed-environment rules).",
    command: ["admin", "list-groups"],
    params: {},
    mutating: false,
  },
  {
    tool: "cs_admin_add_environment_to_group",
    title: "Add an environment to a group",
    description: "Put an environment into an environment group, which applies that group's rules to it. Changes tenant configuration: requires confirm: true.",
    command: ["admin", "add-group"],
    params: {
      environmentGroup: { flag: "--environment-group", type: "string", required: true, description: "Environment group name or id" },
      environment: { flag: "--environment", type: "string", description: "Environment id, url, unique or partial name" },
    },
    mutating: true,
  },
  {
    tool: "cs_admin_list_security_roles",
    title: "List security roles",
    description: "Security roles in an environment, optionally including child roles: what cs_admin_assign_user and cs_admin_assign_group can grant.",
    command: ["admin", "list-roles"],
    params: {
      environment: { flag: "--environment", type: "string", description: "Environment id or URL" },
      businessUnit: { flag: "--business-unit", type: "string", description: "Filter by business unit name or id" },
      includeChildRoles: { flag: "--include-child-roles", type: "boolean", description: "Include child roles" },
    },
    mutating: false,
  },
  {
    tool: "cs_admin_list_service_principals",
    title: "List service principals with Dataverse access",
    description: "Entra applications that have an application user in Dataverse: who can act without a person signing in.",
    command: ["admin", "list-service-principal"],
    params: { filter: { flag: "--filter", type: "string", description: "Application name starts-with filter" }, max: { flag: "--max", type: "number", description: "Maximum applications (default 20)" } },
    mutating: false,
  },
  {
    tool: "cs_admin_list_applications",
    title: "List registered Entra applications",
    description: "Entra applications registered with the tenant for Power Platform.",
    command: ["admin", "application", "list"],
    params: {},
    mutating: false,
  },
  {
    tool: "cs_admin_register_application",
    title: "Register an Entra application",
    description: "Register an Entra application with the tenant so it can be used by Power Platform. Changes tenant configuration: requires confirm: true.",
    command: ["admin", "application", "register"],
    params: { applicationId: { flag: "--application-id", type: "string", required: true, description: "Application (client) id" } },
    mutating: true,
  },
  {
    tool: "cs_admin_unregister_application",
    title: "Unregister an Entra application",
    description: "Remove an Entra application's tenant registration. Changes tenant configuration: requires confirm: true.",
    command: ["admin", "application", "unregister"],
    params: { applicationId: { flag: "--application-id", type: "string", required: true, description: "Application (client) id" } },
    mutating: true,
  },
  {
    tool: "cs_admin_list_app_templates",
    title: "List Dynamics 365 app templates",
    description: "The Dynamics 365 application templates that can be installed when creating an environment, per region.",
    command: ["admin", "list-app-templates"],
    params: { region: { flag: "--region", type: "string", description: "Region name (default unitedstates)" } },
    mutating: false,
  },
  {
    tool: "cs_admin_list_backups",
    title: "List environment backups",
    description: "Backups of an environment, with their labels and dates: what cs_admin_restore_environment can restore.",
    command: ["admin", "list-backups"],
    params: { environment: { flag: "--environment", type: "string", description: "Environment id or URL" } },
    mutating: false,
  },
  {
    tool: "cs_admin_backup_environment",
    title: "Back up an environment",
    description: "Take a manual backup of an environment (the platform's own backup, not the file backup cs_backup_tenant writes). Changes a live environment: requires confirm: true.",
    command: ["admin", "backup"],
    params: { environment: { flag: "--environment", type: "string", description: "Environment id or URL" }, label: { flag: "--label", type: "string", required: true, description: "Backup label" } },
    mutating: true,
    timeoutMs: 60 * 60_000,
  },
  {
    tool: "cs_admin_set_backup_retention",
    title: "Set the backup retention period",
    description: "Set how many days backups of an environment are kept (7, 14, 21 or 28). Changes a live environment: requires confirm: true.",
    command: ["admin", "set-backup-retention-period"],
    params: { environment: { flag: "--environment", type: "string", description: "Environment id or URL" }, days: { flag: "--backup-retention-period", type: "number", required: true, description: "7, 14, 21 or 28" }, ...ASYNC },
    mutating: true,
  },
  {
    tool: "cs_admin_restore_environment",
    title: "Restore an environment from a backup",
    description: "Restore a backup into the same or another environment. Overwrites the target's data and customisations: requires confirm: true.",
    command: ["admin", "restore"],
    params: {
      sourceEnvironment: { flag: "--source-env", type: "string", description: "Environment the backup came from" },
      targetEnvironment: { flag: "--target-env", type: "string", description: "Environment to restore into (defaults to the source)" },
      selectedBackup: { flag: "--selected-backup", type: "string", required: true, description: "Backup date as mm/dd/yyyy hh:mm, or 'latest'" },
      name: { flag: "--name", type: "string", description: "Name for the restored environment" },
      skipAuditData: { flag: "--skip-audit-data", type: "boolean", description: "Do not restore audit data" },
      ...ASYNC,
    },
    mutating: true,
    timeoutMs: 4 * 60 * 60_000,
  },
  {
    tool: "cs_admin_copy_environment",
    title: "Copy one environment over another",
    description: "Copy a source environment onto a target environment. Everything in the target is replaced: requires confirm: true.",
    command: ["admin", "copy"],
    params: {
      sourceEnvironment: { flag: "--source-env", type: "string", description: "Environment to copy from" },
      targetEnvironment: { flag: "--target-env", type: "string", description: "Environment to overwrite" },
      name: { flag: "--name", type: "string", description: "Name for the target environment" },
      type: { flag: "--type", type: "string", description: "Copy type (for example MinimalCopy, FullCopy)" },
      skipAuditData: { flag: "--skip-audit-data", type: "boolean", description: "Do not copy audit data" },
      ...ASYNC,
    },
    mutating: true,
    timeoutMs: 4 * 60 * 60_000,
  },
  {
    tool: "cs_admin_create_environment",
    title: "Create an environment",
    description: "Create a Dataverse environment in the tenant. Consumes tenant capacity: requires confirm: true.",
    command: ["admin", "create"],
    params: {
      name: { flag: "--name", type: "string", description: "Environment name" },
      region: { flag: "--region", type: "string", description: "Region (default unitedstates)" },
      type: { flag: "--type", type: "string", required: true, description: "Production, Sandbox, Trial, Developer or Teams" },
      currency: { flag: "--currency", type: "string", description: "Currency (default USD)" },
      language: { flag: "--language", type: "string", description: "Language (default English)" },
      domain: { flag: "--domain", type: "string", description: "Domain part of the environment URL" },
      templates: { flag: "--templates", type: "string[]", join: "comma", description: "Dynamics 365 templates to deploy" },
      securityGroupId: { flag: "--security-group-id", type: "string", description: "Entra security group id (required for a Teams environment)" },
      user: { flag: "--user", type: "string", description: "User to assign to the environment (object id or UPN)" },
      inputFile: { flag: "--input-file", type: "string", description: "JSON file with the arguments" },
      ...ASYNC,
    },
    mutating: true,
    timeoutMs: 2 * 60 * 60_000,
  },
  {
    tool: "cs_admin_delete_environment",
    title: "Delete an environment",
    description: "Delete an environment from the tenant, with everything in it: agents, solutions, flows and data. Irreversible beyond the platform's own backup retention: requires confirm: true.",
    command: ["admin", "delete"],
    params: { environment: { flag: "--environment", type: "string", description: "Environment id or URL" }, ...ASYNC },
    mutating: true,
    timeoutMs: 2 * 60 * 60_000,
  },
  {
    tool: "cs_admin_reset_environment",
    title: "Reset an environment",
    description: "Reset an environment to an empty Dataverse instance. Everything in it is deleted: requires confirm: true.",
    command: ["admin", "reset"],
    params: {
      environment: { flag: "--environment", type: "string", description: "Environment id or URL" },
      name: { flag: "--name", type: "string", description: "New name" },
      currency: { flag: "--currency", type: "string", description: "Currency" },
      language: { flag: "--language", type: "string", description: "Language" },
      domain: { flag: "--domain", type: "string", description: "Domain part of the URL" },
      purpose: { flag: "--purpose", type: "string", description: "Description of the environment's intent" },
      templates: { flag: "--templates", type: "string[]", join: "comma", description: "Dynamics 365 templates" },
      inputFile: { flag: "--input-file", type: "string", description: "JSON file with the arguments" },
      ...ASYNC,
    },
    mutating: true,
    timeoutMs: 2 * 60 * 60_000,
  },
  {
    tool: "cs_admin_set_runtime_state",
    title: "Set environment administration mode",
    description: "Put an environment into administration mode (only admins can use it) or back, and control background operations. Changes a live environment: requires confirm: true.",
    command: ["admin", "set-runtime-state"],
    params: {
      environment: { flag: "--environment", type: "string", required: true, description: "Environment id or URL" },
      runtimeState: { flag: "--runtime-state", type: "string", required: true, description: "AdminMode or Enabled" },
      backgroundOperations: { flag: "--background-operations", type: "string", description: "Background operations state" },
      ...ASYNC,
    },
    mutating: true,
  },
  {
    tool: "cs_admin_set_governance_config",
    title: "Enable or edit managed environments",
    description: "Turn managed environments on ('Standard') or off ('Basic') for an environment and set its governance options: sharing limits, solution checker mode, maker onboarding. Changes tenant governance: requires confirm: true.",
    command: ["admin", "set-governance-config"],
    params: {
      environment: { flag: "--environment", type: "string", required: true, description: "Environment id or URL" },
      protectionLevel: { flag: "--protection-level", type: "string", required: true, values: ["Standard", "Basic"], description: "Standard enables managed environments, Basic disables them" },
      disableGroupSharing: { flag: "--disable-group-sharing", type: "boolean", description: "Disable sharing with groups" },
      limitSharingMode: { flag: "--limit-sharing-mode", type: "string", description: "Sharing limit mode" },
      maxLimitUserSharing: { flag: "--max-limit-user-sharing", type: "number", description: "How many people makers may share canvas apps with" },
      solutionCheckerMode: { flag: "--solution-checker-mode", type: "string", description: "Solution checker validation mode (None, Warn, Block)" },
      checkerRuleOverrides: { flag: "--checker-rule-overrides", type: "string", description: "Solution checker rule overrides" },
      suppressValidationEmails: { flag: "--suppress-validation-emails", type: "boolean", description: "Do not send validation emails" },
      cloudFlowsMode: { flag: "--cloud-flows-mode", type: "string", description: "Sharing limit mode for solution cloud flows" },
      cloudFlowsLimit: { flag: "--cloud-flows-limit", type: "number", description: "How many people makers may share solution cloud flows with" },
      makerOnboardingUrl: { flag: "--maker-onboarding-url", type: "string", description: "Maker onboarding URL" },
      makerOnboardingMarkdown: { flag: "--maker-onboarding-markdown", type: "string", description: "Maker onboarding markdown" },
      excludeAnalysis: { flag: "--exclude-analysis", type: "boolean", description: "Exclude this environment from the weekly usage digest" },
      includeInsights: { flag: "--include-insights", type: "boolean", description: "Show insights on the admin centre home page" },
    },
    mutating: true,
  },
  {
    tool: "cs_admin_assign_user",
    title: "Assign a user to an environment",
    description: "Give a user (or an application user) a security role in an environment. Changes a live environment: requires confirm: true.",
    command: ["admin", "assign-user"],
    params: {
      environment: { flag: "--environment", type: "string", description: "Environment id or URL" },
      user: { flag: "--user", type: "string", required: true, description: "Object id or UPN, or the application id for an application user" },
      role: { flag: "--role", type: "string", required: true, description: "Security role name or id (cs_admin_list_security_roles)" },
      applicationUser: { flag: "--application-user", type: "boolean", description: "The user is an application (service principal)" },
      businessUnit: { flag: "--business-unit", type: "string", description: "Business unit id" },
    },
    mutating: true,
  },
  {
    tool: "cs_admin_assign_group",
    title: "Assign a group to an environment",
    description: "Give an Entra group a security role in an environment through a Dataverse team. Changes a live environment: requires confirm: true.",
    command: ["admin", "assign-group"],
    params: {
      environment: { flag: "--environment", type: "string", description: "Environment id or URL" },
      group: { flag: "--group", type: "string", required: true, description: "Entra group object id" },
      groupName: { flag: "--group-name", type: "string", required: true, description: "Name of the Dataverse team to create" },
      role: { flag: "--role", type: "string", required: true, description: "Security role name or id" },
      teamType: { flag: "--team-type", type: "string", required: true, description: "Team type (Owner, Access, AadSecurityGroup, AadOfficeGroup)" },
      membershipType: { flag: "--membership-type", type: "string", required: true, description: "Membership type (MembersAndGuests, Members, Owners, Guests)" },
      businessUnit: { flag: "--business-unit", type: "string", description: "Business unit id" },
    },
    mutating: true,
  },
  {
    tool: "cs_admin_create_service_principal",
    title: "Create an application user",
    description: "Register an Entra application and give it an application user with a security role in an environment: the headless identity a pipeline signs in as. Changes a live environment: requires confirm: true.",
    command: ["admin", "create-service-principal"],
    params: {
      environment: { flag: "--environment", type: "string", description: "Environment id or URL" },
      name: { flag: "--name", type: "string", description: "Application name to create in Entra" },
      role: { flag: "--role", type: "string", description: "Security role (default System Administrator)" },
    },
    mutating: true,
  },
  {
    tool: "cs_admin_self_elevate",
    title: "Self-elevate to System Administrator",
    description: "Give yourself the System Administrator role in an environment. Needs Global, Power Platform or Dynamics 365 admin. Changes a live environment: requires confirm: true.",
    command: ["admin", "self-elevate"],
    params: { environment: { flag: "--environment", type: "string", description: "Environment id or URL" } },
    mutating: true,
  },
  {
    tool: "cs_admin_query",
    title: "Run a tenant resource query",
    description: "Run a tenant-level resource query (the admin centre's own query language) and optionally write the results to a file as JSON, list or CSV.",
    command: ["admin", "query"],
    params: {
      query: { flag: "--query", type: "string", description: "Resource query JSON as a string" },
      queryFile: { flag: "--query-file", type: "string", description: "File containing the query JSON" },
      outputType: { flag: "--output-type", type: "string", values: ["Json", "List", "Grid"], description: "Json, List or Grid (default Grid)" },
      outputFile: { flag: "--output-file", type: "string", description: "Where to save the results" },
    },
    mutating: false,
  }
];
